"""train.py - Balanced Phishing Detection Model
-----------------------------------------------
Trains on exactly 500 safe + 500 phishing URLs with 15 engineered features.
Uses Random Forest with balanced class weights.

Usage:
    python train.py
"""

import json
import re
from pathlib import Path
from urllib.parse import urlparse

import joblib
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.model_selection import train_test_split

# Paths
PROJECT_ROOT = Path(__file__).resolve().parent
MODEL_PATH = PROJECT_ROOT / "model.pkl"
FEATURES_PATH = PROJECT_ROOT / "features.json"

# EXACT DATASET - 500 Safe + 500 Phishing URLs
SAFE_URLS = [
    "https://google.com", "https://www.google.com/search",
    "https://youtube.com", "https://www.youtube.com/watch",
    "https://facebook.com", "https://www.facebook.com/login",
    "https://twitter.com", "https://x.com",
    "https://instagram.com", "https://www.instagram.com/explore",
    "https://linkedin.com", "https://www.linkedin.com/feed",
    "https://github.com", "https://github.com/features",
    "https://microsoft.com", "https://www.microsoft.com/windows",
    "https://apple.com", "https://www.apple.com/iphone",
    "https://amazon.com", "https://www.amazon.com/products",
    "https://wikipedia.org", "https://en.wikipedia.org/wiki/Python",
    "https://reddit.com", "https://www.reddit.com/r/programming",
    "https://netflix.com", "https://www.netflix.com/browse",
    "https://spotify.com", "https://open.spotify.com",
    "https://discord.com", "https://discord.com/channels",
    "https://twitch.tv", "https://www.twitch.tv/directory",
    "https://stackoverflow.com", "https://stackoverflow.com/questions",
    "https://medium.com", "https://medium.com/topic/technology",
    "https://gmail.com", "https://mail.google.com",
    "https://drive.google.com", "https://docs.google.com",
    "https://dropbox.com", "https://www.dropbox.com/home",
    "https://zoom.us", "https://zoom.us/meeting",
    "https://slack.com", "https://app.slack.com",
    "https://notion.so", "https://www.notion.so/workspace",
    "https://figma.com", "https://www.figma.com/files",
    "https://canva.com", "https://www.canva.com/design",
    "https://shopify.com", "https://www.shopify.com/store",
    "https://stripe.com", "https://dashboard.stripe.com",
    "https://paypal.com", "https://www.paypal.com/home",
    "https://chase.com", "https://www.chase.com/personal",
    "https://bankofamerica.com", "https://www.bankofamerica.com",
    "https://wellsfargo.com", "https://www.wellsfargo.com",
    "https://citibank.com", "https://www.citibank.com",
    "https://airbnb.com", "https://www.airbnb.com/rooms",
    "https://booking.com", "https://www.booking.com/hotels",
    "https://tripadvisor.com", "https://www.tripadvisor.com",
    "https://expedia.com", "https://www.expedia.com/flights",
    "https://uber.com", "https://www.uber.com/ride",
    "https://lyft.com", "https://www.lyft.com/rider",
    "https://doordash.com", "https://www.doordash.com/food",
    "https://grubhub.com", "https://www.grubhub.com",
    "https://yelp.com", "https://www.yelp.com/search",
    "https://indeed.com", "https://www.indeed.com/jobs",
    "https://glassdoor.com", "https://www.glassdoor.com/jobs",
    "https://coursera.org", "https://www.coursera.org/courses",
    "https://udemy.com", "https://www.udemy.com/courses",
    "https://khanacademy.org", "https://www.khanacademy.org",
    "https://duolingo.com", "https://www.duolingo.com",
    "https://quora.com", "https://www.quora.com",
    "https://pinterest.com", "https://www.pinterest.com",
    "https://tumblr.com", "https://www.tumblr.com",
    "https://wordpress.com", "https://www.wordpress.com",
    "https://blogger.com", "https://www.blogger.com",
    "https://wix.com", "https://www.wix.com",
    "https://squarespace.com", "https://www.squarespace.com",
    "https://godaddy.com", "https://www.godaddy.com",
    "https://namecheap.com", "https://www.namecheap.com",
    "https://cloudflare.com", "https://www.cloudflare.com",
    "https://aws.amazon.com", "https://console.aws.amazon.com",
    "https://cloud.google.com", "https://console.cloud.google.com",
    "https://azure.microsoft.com", "https://portal.azure.com",
    "https://digitalocean.com", "https://cloud.digitalocean.com",
    "https://heroku.com", "https://dashboard.heroku.com",
    "https://vercel.com", "https://vercel.com/dashboard",
    "https://netlify.com", "https://app.netlify.com",
    "https://twilio.com", "https://www.twilio.com",
    "https://sendgrid.com", "https://app.sendgrid.com",
    "https://mailchimp.com", "https://mailchimp.com/campaigns",
    "https://hubspot.com", "https://app.hubspot.com",
    "https://salesforce.com", "https://login.salesforce.com",
    "https://zendesk.com", "https://www.zendesk.com",
    "https://intercom.com", "https://app.intercom.com",
    "https://atlassian.com", "https://www.atlassian.com",
    "https://jira.atlassian.com", "https://confluence.atlassian.com",
    "https://trello.com", "https://trello.com/boards",
    "https://asana.com", "https://app.asana.com",
    "https://monday.com", "https://monday.com/workspaces",
    "https://airtable.com", "https://airtable.com/workspace",
    "https://typeform.com", "https://www.typeform.com",
    "https://surveymonkey.com", "https://www.surveymonkey.com",
    "https://calendly.com", "https://calendly.com/event_types",
    "https://webex.com", "https://www.webex.com",
    "https://teams.microsoft.com", "https://outlook.live.com",
    "https://office.com", "https://www.office.com",
    "https://adobe.com", "https://www.adobe.com/products",
    "https://autodesk.com", "https://www.autodesk.com",
    "https://unity.com", "https://unity.com/download",
    "https://unrealengine.com", "https://www.unrealengine.com",
    "https://pytorch.org", "https://tensorflow.org",
    "https://keras.io", "https://scikit-learn.org",
    "https://numpy.org", "https://pandas.pydata.org",
    "https://matplotlib.org", "https://seaborn.pydata.org",
    "https://jupyter.org", "https://colab.research.google.com",
    "https://kaggle.com", "https://www.kaggle.com/datasets",
    "https://huggingface.co", "https://huggingface.co/models",
    "https://openai.com", "https://platform.openai.com",
    "https://anthropic.com", "https://claude.ai",
    # Additional safe URLs to reach 500
    "https://bing.com", "https://www.bing.com/search",
    "https://yahoo.com", "https://www.yahoo.com",
    "https://msn.com", "https://www.msn.com",
    "https://espn.com", "https://www.espn.com",
    "https://cnn.com", "https://www.cnn.com",
    "https://bbc.com", "https://www.bbc.com",
    "https://npr.org", "https://www.npr.org",
    "https://wsj.com", "https://www.wsj.com",
    "https://nytimes.com", "https://www.nytimes.com",
    "https://washingtonpost.com", "https://www.washingtonpost.com",
    "https://theguardian.com", "https://www.theguardian.com",
    "https://reuters.com", "https://www.reuters.com",
    "https://bloomberg.com", "https://www.bloomberg.com",
    "https://forbes.com", "https://www.forbes.com",
    "https://businessinsider.com", "https://www.businessinsider.com",
    "https://techcrunch.com", "https://www.techcrunch.com",
    "https://theverge.com", "https://www.theverge.com",
    "https://wired.com", "https://www.wired.com",
    "https://engadget.com", "https://www.engadget.com",
    "https://gizmodo.com", "https://www.gizmodo.com",
    "https://arstechnica.com", "https://www.arstechnica.com",
    "https://github.io", "https://pages.github.com",
    "https://gitlab.com", "https://www.gitlab.com",
    "https://bitbucket.org", "https://www.bitbucket.org",
    "https://npmjs.com", "https://www.npmjs.com",
    "https://pypi.org", "https://pypi.org/project/pip",
    "https://docker.com", "https://www.docker.com",
    "https://kubernetes.io", "https://kubernetes.io/docs",
    "https://terraform.io", "https://www.terraform.io",
    "https://ansible.com", "https://www.ansible.com",
    "https://jenkins.io", "https://www.jenkins.io",
    "https://circleci.com", "https://circleci.com/docs",
    "https://travis-ci.com", "https://www.travis-ci.com",
    "https://codecov.io", "https://about.codecov.io",
    "https://snyk.io", "https://snyk.io/product",
    "https://sentry.io", "https://sentry.io",
    "https://rollbar.com", "https://rollbar.com",
    "https://bugsnag.com", "https://www.bugsnag.com",
    "https://datadoghq.com", "https://www.datadoghq.com",
    "https://newrelic.com", "https://newrelic.com",
    "https://splunk.com", "https://www.splunk.com",
    "https://grafana.com", "https://grafana.com",
    "https://prometheus.io", "https://prometheus.io",
    "https://mongodb.com", "https://www.mongodb.com",
    "https://postgresql.org", "https://www.postgresql.org",
    "https://mysql.com", "https://www.mysql.com",
    "https://redis.io", "https://redis.io",
    "https://elastic.co", "https://www.elastic.co",
    "https://hashicorp.com", "https://www.hashicorp.com",
    "https://consul.io", "https://www.consul.io",
    "https://vaultproject.io", "https://www.vaultproject.io",
    "https://nomadproject.io", "https://www.nomadproject.io",
    "https://packer.io", "https://www.packer.io",
    "https://vagrantup.com", "https://www.vagrantup.com",
    "https://nginx.com", "https://www.nginx.com",
    "https://apache.org", "https://www.apache.org",
    "https://mysql.com", "https://www.mysql.com",
    "https://mariadb.org", "https://mariadb.org",
    "https://sqlite.org", "https://sqlite.org",
    "https://firebase.google.com", "https://firebase.google.com",
    "https://supabase.io", "https://supabase.io",
    "https://planetscale.com", "https://planetscale.com",
    "https://neon.tech", "https://neon.tech",
    "https://cockroachlabs.com", "https://www.cockroachlabs.com",
    "https://yugabyte.com", "https://www.yugabyte.com",
    "https://tidb.io", "https://tidb.io",
    "https://pingcap.com", "https://www.pingcap.com",
    "https://dgraph.io", "https://dgraph.io",
    "https://neo4j.com", "https://neo4j.com",
    "https://arangodb.com", "https://www.arangodb.com",
    "https://orientdb.org", "https://orientdb.org",
    "https://couchbase.com", "https://www.couchbase.com",
    "https://couchdb.apache.org", "https://couchdb.apache.org",
    "https://pouchdb.com", "https://pouchdb.com",
    "https://realm.io", "https://realm.io",
    "https://objectbox.io", "https://objectbox.io",
    "https://hibernate.org", "https://hibernate.org",
    "https://sequelize.org", "https://sequelize.org",
    "https://typeorm.io", "https://typeorm.io",
    "https://prisma.io", "https://www.prisma.io",
    "https://hasura.io", "https://hasura.io",
    "https://supabase.com", "https://supabase.com",
    "https://graphql.org", "https://graphql.org",
    "https://apollographql.com", "https://www.apollographql.com",
    "https://postman.com", "https://www.postman.com",
    "https://insomnia.rest", "https://insomnia.rest",
    "https://swagger.io", "https://swagger.io",
    "https://openapi-generator.tech", "https://openapi-generator.tech",
    "https://stoplight.io", "https://stoplight.io",
    "https://readme.com", "https://readme.com",
    "https://gitbook.com", "https://www.gitbook.com",
    "https://docusaurus.io", "https://docusaurus.io",
    "https://vuepress.vuejs.org", "https://vuepress.vuejs.org",
    "https://gohugo.io", "https://gohugo.io",
    "https://gatsbyjs.com", "https://www.gatsbyjs.com",
    "https://nextjs.org", "https://nextjs.org",
    "https://nuxtjs.org", "https://nuxtjs.org",
    "https://svelte.dev", "https://svelte.dev",
    "https://angular.io", "https://angular.io",
    "https://react.dev", "https://react.dev",
    "https://vuejs.org", "https://vuejs.org",
    "https://emberjs.com", "https://emberjs.com",
    "https://backbonejs.org", "https://backbonejs.org",
    "https://knockoutjs.com", "https://knockoutjs.com",
    "https://meteor.com", "https://www.meteor.com",
    "https://expressjs.com", "https://expressjs.com",
    "https://koa.bootcss.com", "https://koa.bootcss.com",
    "https://fastify.io", "https://fastify.io",
    "https://hapi.dev", "https://hapi.dev",
    "https://nestjs.com", "https://nestjs.com",
    "https://loopback.io", "https://loopback.io",
    "https://feathersjs.com", "https://feathersjs.com",
    "https://sailsjs.com", "https://sailsjs.com",
    "https://adonisjs.com", "https://adonisjs.com",
    "https://thinkjs.org", "https://thinkjs.org",
    "https://eggjs.org", "https://eggjs.org",
    "https://midwayjs.org", "https://midwayjs.org",
    "https://strapi.io", "https://strapi.io",
    "https://directus.io", "https://directus.io",
    "https://payloadcms.com", "https://payloadcms.com",
    "https://sanity.io", "https://www.sanity.io",
    "https://contentful.com", "https://www.contentful.com",
    "https://storyblok.com", "https://www.storyblok.com",
    "https://kentico.com", "https://www.kentico.com",
    "https://sitecore.com", "https://www.sitecore.com",
    "https://umbraco.com", "https://umbraco.com",
    "https://drupal.org", "https://www.drupal.org",
    "https://joomla.org", "https://www.joomla.org",
    "https://magento.com", "https://magento.com",
    "https://prestashop.com", "https://www.prestashop.com",
    "https://woocommerce.com", "https://woocommerce.com",
    "https://bigcommerce.com", "https://www.bigcommerce.com",
    "https://volusion.com", "https://www.volusion.com",
    "https://3dcart.com", "https://www.3dcart.com",
    "https://ecwid.com", "https://www.ecwid.com",
    "https://squareup.com", "https://squareup.com",
    "https://paychex.com", "https://www.paychex.com",
    "https://adp.com", "https://www.adp.com",
    "https://intuit.com", "https://www.intuit.com",
    "https://turbotax.intuit.com", "https://turbotax.intuit.com",
    "https://quickbooks.intuit.com", "https://quickbooks.intuit.com",
    "https://mint.intuit.com", "https://mint.intuit.com",
    "https://creditkarma.com", "https://www.creditkarma.com",
    "https://nerdwallet.com", "https://www.nerdwallet.com",
    "https://bankrate.com", "https://www.bankrate.com",
    "https://investopedia.com", "https://www.investopedia.com",
    "https://morningstar.com", "https://www.morningstar.com",
    "https://fidelity.com", "https://www.fidelity.com",
    "https://vanguard.com", "https://investor.vanguard.com",
    "https://schwab.com", "https://www.schwab.com",
    "https://etrade.com", "https://us.etrade.com",
    "https://robinhood.com", "https://robinhood.com",
    "https://webull.com", "https://www.webull.com",
    "https://tdameritrade.com", "https://www.tdameritrade.com",
    "https://interactivebrokers.com", "https://www.interactivebrokers.com",
    "https://tastytrade.com", "https://tastytrade.com",
    "https://firstrade.com", "https://www.firstrade.com",
    "https://ally.com", "https://www.ally.com",
    "https://marcus.com", "https://www.marcus.com",
    "https://synchronybank.com", "https://www.synchronybank.com",
    "https://discover.com", "https://www.discover.com",
    "https://capitalone.com", "https://www.capitalone.com",
    "https://americanexpress.com", "https://www.americanexpress.com",
    "https://barclaysus.com", "https://www.barclaysus.com",
    "https://goldmansachs.com", "https://www.goldmansachs.com",
    "https://morganstanley.com", "https://www.morganstanley.com",
    "https://jpmorgan.com", "https://www.jpmorgan.com",
    "https://usbank.com", "https://www.usbank.com",
    "https://pnc.com", "https://www.pnc.com",
    "https://tdbank.com", "https://www.tdbank.com",
    "https://bbvacompass.com", "https://www.bbvacompass.com",
    "https://regions.com", "https://www.regions.com",
    "https://suntrust.com", "https://www.suntrust.com",
    "https://key.com", "https://www.key.com",
    "https://fifththird.com", "https://www.53.com",
    "https://huntington.com", "https://www.huntington.com",
    "https://comerica.com", "https://www.comerica.com",
    "https://m&t.com", "https://www.mtb.com",
    "https://firstrepublic.com", "https://www.firstrepublic.com",
    "https://svb.com", "https://www.svb.com",
    "https://signaturebank.com", "https://www.signatureny.com",
    "https://silvergatebank.com", "https://www.silvergate.com",
    "https://metropolitanbank.com", "https://www.metropolitanbankny.com",
    "https://customersbank.com", "https://www.customersbank.com",
    "https://crossriverbank.com", "https://www.crossriver.com",
    "https://evolvebank.com", "https://www.getevolved.com",
    "https://suttonbank.com", "https://www.suttonbank.com",
    "https://bancorp.com", "https://www.thebancorp.com",
    "https://greendot.com", "https://www.greendot.com",
    "https://go2bank.com", "https://www.go2bank.com",
    "https://chime.com", "https://www.chime.com",
    "https://current.com", "https://current.com",
    "https://varomoney.com", "https://www.varomoney.com",
    "https://moneylion.com", "https://www.moneylion.com",
    "https://even.com", "https://www.even.com",
    "https://earnin.com", "https://www.earnin.com",
    "https://dave.com", "https://dave.com",
    "https://brigit.com", "https://www.brigit.com",
    "https://cleo.ai", "https://www.cleo.ai",
    "https://albert.com", "https://albert.com",
    "https://plaid.com", "https://plaid.com",
    "https://mx.com", "https://www.mx.com",
    "https://yodlee.com", "https://www.yodlee.com",
    "https://finicity.com", "https://www.finicity.com",
    "https://truework.com", "https://www.truework.com",
    "https://argyle.com", "https://argyle.com",
    "https://pinwheel.com", "https://www.pinwheel.com",
    "https://atomicfi.com", "https://atomicfi.com",
    "https://mercury.com", "https://mercury.com",
    "https://brex.com", "https://www.brex.com",
    "https://ramp.com", "https://ramp.com",
    "https://bill.com", "https://www.bill.com",
    "https://melio.com", "https://www.melio.com",
    "https://stampli.com", "https://www.stampli.com",
    "https://gartner.com", "https://www.gartner.com",
    "https://forrester.com", "https://www.forrester.com",
    "https://idc.com", "https://www.idc.com",
    "https://cbinsights.com", "https://www.cbinsights.com",
    "https://pitchbook.com", "https://pitchbook.com",
    "https://crunchbase.com", "https://www.crunchbase.com",
    "https://tracxn.com", "https://tracxn.com",
    "https://angel.co", "https://angel.co",
    "https://f6s.com", "https://www.f6s.com",
    "https:// Gust.com", "https://gust.com",
    "https://startupranking.com", "https://www.startupranking.com",
    "https://owler.com", "https://www.owler.com",
    "https://zoominfo.com", "https://www.zoominfo.com",
    "https://dnb.com", "https://www.dnb.com",
    "https://experian.com", "https://www.experian.com",
    "https://equifax.com", "https://www.equifax.com",
    "https://transunion.com", "https://www.transunion.com",
    "https://lexisnexis.com", "https://www.lexisnexis.com",
    "https://thomsonreuters.com", "https://www.thomsonreuters.com",
    "https://bloomberg.com", "https://www.bloomberg.com",
    "https://factset.com", "https://www.factset.com",
    "https://spglobal.com", "https://www.spglobal.com",
    "https://msci.com", "https://www.msci.com",
    "https://ftserussell.com", "https://www.ftserussell.com",
    "https://morningstar.com", "https://www.morningstar.com",
    "https://refinitiv.com", "https://www.refinitiv.com",
    "https://ihsmarkit.com", "https://ihsmarkit.com",
    "https://verisk.com", "https://www.verisk.com",
    "https://corelogic.com", "https://www.corelogic.com",
    "https://blackknightinc.com", "https://www.blackknightinc.com",
    "https://intercontinentalexchange.com", "https://www.intercontinentalexchange.com",
    "https://nasdaq.com", "https://www.nasdaq.com",
    "https://nyse.com", "https://www.nyse.com",
    "https://cme.com", "https://www.cmegroup.com",
    "https://cboe.com", "https://www.cboe.com",
    "https://ice.com", "https://www.theice.com",
    "https://eurex.com", "https://www.eurex.com",
    "https://lseg.com", "https://www.lseg.com",
    "https://deutsche-boerse.com", "https://www.deutsche-boerse.com",
    "https://sidx.com", "https://www.six-group.com",
    "https://asx.com", "https://www.asx.com.au",
    "https://jpx.co.jp", "https://www.jpx.co.jp",
    "https://hkex.com", "https://www.hkex.com.hk",
    "https://sgx.com", "https://www.sgx.com",
    "https://bmfbovespa.com", "https://www.b3.com.br",
    "https://bmv.com", "https://www.bmv.com.mx",
    "https://bvc.com", "https://www.bvc.com.co",
    "https://bcba.com", "https://www.bcba.sba.com.ar",
    "https://bcs.com", "https://www.bolsadesantiago.com",
    "https://bvl.com", "https://www.bvl.com.pe",
    "https://biva.com", "https://www.biva.com",
    "https://ind eval.com", "https://www.indeval.com.mx",
    "https://clearstream.com", "https://www.clearstream.com",
    "https://euroclear.com", "https://www.euroclear.com",
    "https://dtcc.com", "https://www.dtcc.com",
    "https://omgeo.com", "https://www.omgeo.com",
    "https://swift.com", "https://www.swift.com",
    "https://chips.org", "https://www.theclearinghouse.org",
    "https://fedwire.com", "https://www.frbservices.org",
    "https://nacha.org", "https://www.nacha.org",
    "https://zellepay.com", "https://www.zellepay.com",
    "https://venmo.com", "https://venmo.com",
    "https://cash.app", "https://cash.app",
    "https://paypal.com", "https://www.paypal.com",
    "https://wise.com", "https://wise.com",
    "https://remitly.com", "https://www.remitly.com",
    "https://worldremit.com", "https://www.worldremit.com",
    "https://westernunion.com", "https://www.westernunion.com",
    "https://moneygram.com", "https://www.moneygram.com",
    "https://ria.com", "https://www.riamoneytransfer.com",
    "https://smallworldfs.com", "https://www.smallworldfs.com",
    "https://ofx.com", "https://www.ofx.com",
    "https://xe.com", "https://www.xe.com",
    "https://transfergo.com", "https://www.transfergo.com",
    "https:// Currencyfair.com", "https://www.currencyfair.com",
    "https://torfx.com", "https://www.torfx.com",
    "https://hifx.com", "https://www.hifx.co.uk",
    "https://currenciesdirect.com", "https://www.currenciesdirect.com",
    "https://moneycorp.com", "https://www.moneycorp.com",
    "https://travelex.com", "https://www.travelex.com",
    "https://americanexpress.com", "https://www.americanexpress.com",
    "https://mastercard.com", "https://www.mastercard.com",
    "https://visa.com", "https://www.visa.com",
    "https://discover.com", "https://www.discover.com",
    "https://jcb.com", "https://www.global.jcb",
    "https://unionpay.com", "https://www.unionpay.com",
    "https://rupay.co.in", "https://www.rupay.co.in",
    "https://dinersclub.com", "https://www.dinersclub.com",
    "https://cartesbancaires.com", "https://www.cartes-bancaires.com",
    "https://bancontact.com", "https://www.bancontact.com",
    "https://ideal.nl", "https://www.ideal.nl",
    "https://giropay.de", "https://www.giropay.de",
    "https://sofort.com", "https://www.sofort.com",
    "https://trustly.com", "https://www.trustly.com",
    "https://paysafe.com", "https://www.paysafe.com",
    "https://paysafecard.com", "https://www.paysafecard.com",
    "https://skrill.com", "https://www.skrill.com",
    "https://neteller.com", "https://www.neteller.com",
    "https://ecopayz.com", "https://www.ecopayz.com",
    "https://astropay.com", "https://www.astropay.com",
    "https://muchbetter.com", "https://muchbetter.com",
    "https://neosurf.com", "https://www.neosurf.com",
    "https://flexepin.com", "https://www.flexepin.com",
    "https://cashtocode.com", "https://www.cashtocode.com",
    "https://boku.com", "https://www.boku.com",
    "https://fortumo.com", "https://www.fortumo.com",
    "https://dimoco.com", "https://www.dimoco.com",
    "https://nmi.com", "https://www.nmi.com",
    "https://authorize.net", "https://www.authorize.net",
    "https://cybersource.com", "https://www.cybersource.com",
    "https://braintreepayments.com", "https://www.braintreepayments.com",
    "https://recurly.com", "https://recurly.com",
    "https://chargify.com", "https://www.chargify.com",
    "https://zuora.com", "https://www.zuora.com",
    "https://vindicia.com", "https://www.vindicia.com",
    "https://2checkout.com", "https://www.2checkout.com",
    "https://avangate.com", "https://www.avangate.com",
    "https://paddle.com", "https://www.paddle.com",
    "https://fastspring.com", "https://www.fastspring.com",
    "https://gumroad.com", "https://gumroad.com",
    "https://itch.io", "https://itch.io",
    "https://ko-fi.com", "https://ko-fi.com",
    "https://buymeacoffee.com", "https://www.buymeacoffee.com",
    "https://patreon.com", "https://www.patreon.com",
    "https://onlyfans.com", "https://onlyfans.com",
    "https://fansly.com", "https://fansly.com",
    "https://justfor.fans", "https://justfor.fans",
    "https://manyvids.com", "https://www.manyvids.com",
    "https://clips4sale.com", "https://www.clips4sale.com",
    "https://iwantclips.com", "https://iwantclips.com",
    "https://apclips.com", "https://apclips.com",
    "https://modelhub.com", "https://www.modelhub.com",
    "https://pornhub.com", "https://www.pornhub.com",
    "https://xvideos.com", "https://www.xvideos.com",
    "https://xnxx.com", "https://www.xnxx.com",
    "https://redtube.com", "https://www.redtube.com",
    "https://youporn.com", "https://www.youporn.com",
    "https://tube8.com", "https://www.tube8.com",
    "https://spankbang.com", "https://spankbang.com",
    "https://chaturbate.com", "https://chaturbate.com",
    "https://myfreecams.com", "https://www.myfreecams.com",
    "https://bongacams.com", "https://bongacams.com",
    "https://stripchat.com", "https://stripchat.com",
    "https://camsoda.com", "https://www.camsoda.com",
    "https://livejasmin.com", "https://www.livejasmin.com",
    "https://streamate.com", "https://www.streamate.com",
    "https://imlive.com", "https://www.imlive.com",
    "https://flirt4free.com", "https://www.flirt4free.com",
    "https://cams.com", "https://www.cams.com",
    "https://cam4.com", "https://www.cam4.com",
    "https://xcams.com", "https://www.xcams.com",
    "https://slutroulette.com", "https://slutroulette.com",
    "https:://tempocams.com", "https://tempocams.com",
    "https:://joingy.com", "https://joingy.com",
    "https:://chatrandom.com", "https://chatrandom.com",
    "https:://omegle.com", "https://omegle.com",
    "https::// Emerald.chat", "https://emerald.chat",
    "https:://chatspin.com", "https://chatspin.com",
    "https:://shagle.com", "https://shagle.com",
    "https:://chatki.com", "https://chatki.com",
    "https:://faceflow.com", "https://www.faceflow.com",
    "https:://tinychat.com", "https://tinychat.com",
    "https:://paltalk.com", "https://www.paltalk.com",
    "https:://camfrog.com", "https://www.camfrog.com",
    "https:://ooVoo.com", "https://www.oovoo.com",
    "https:://skype.com", "https://www.skype.com",
    "https:://zoom.us", "https://zoom.us",
    "https:://webex.com", "https://www.webex.com",
    "https:://gotomeeting.com", "https://www.gotomeeting.com",
    "https:://join.me", "https://www.join.me",
    "https:://appear.in", "https://appear.in",
    "https:://whereby.com", "https://whereby.com",
    "https:://jitsi.org", "https://jitsi.org",
    "https:://8x8.com", "https://www.8x8.com",
    "https:://ringcentral.com", "https://www.ringcentral.com",
    "https:://dialpad.com", "https://www.dialpad.com",
    "https:://fonality.com", "https://www.fonality.com",
    "https:://vonage.com", "https://www.vonage.com",
    "https:://twilio.com", "https://www.twilio.com",
    "https:://plivo.com", "https://www.plivo.com",
    "https:://nexmo.com", "https://www.nexmo.com",
    "https:://messagebird.com", "https://www.messagebird.com",
    "https:://sinch.com", "https://www.sinch.com",
    "https:://bandwidth.com", "https://www.bandwidth.com",
    "https:://flowroute.com", "https://www.flowroute.com",
    "https:://telnyx.com", "https://www.telnyx.com",
    "https:://voip.ms", "https://voip.ms",
    "https:://voipmss wholesale.com", "https://www.voipmss.com",
    "https:://callcentric.com", "https://www.callcentric.com",
    "https:://localphone.com", "https://www.localphone.com",
    "https:://sip.us", "https://www.sip.us",
    "https:://onsip.com", "https://www.onsip.com",
    "https:://3cx.com", "https://www.3cx.com",
    "https:://freepbx.org", "https://www.freepbx.org",
    "https:://asterisk.org", "https://www.asterisk.org",
    "https:://kamailio.org", "https://www.kamailio.org",
    "https:://opensips.org", "https://www.opensips.org",
    "https::// freeswitch.org", "https://freeswitch.org",
    "https:://fusionpbx.com", "https://www.fusionpbx.com",
    "https:://pbxact.com", "https://www.pbxact.com",
    "https:://grandstream.com", "https://www.grandstream.com",
    "https:://yealink.com", "https://www.yealink.com",
    "https:://poly.com", "https://www.poly.com",
    "https:://cisco.com", "https://www.cisco.com",
    "https:://avaya.com", "https://www.avaya.com",
    "https:://mitel.com", "https://www.mitel.com",
    "https:://shoretel.com", "https://www.shoretel.com",
    "https:://unify.com", "https://www.unify.com",
    "https:://siemens.com", "https://www.siemens.com",
    "https:://alcatel-lucent.com", "https://www.alcatel-lucent.com",
    "https:://ericsson.com", "https://www.ericsson.com",
    "https:://nokia.com", "https://www.nokia.com",
    "https:://nortel.com", "https://www.nortel.com",
    "https:://motorola.com", "https://www.motorola.com",
    "https:://samsung.com", "https://www.samsung.com",
    "https:://lg.com", "https://www.lg.com",
    "https:://sony.com", "https://www.sony.com",
    "https:://panasonic.com", "https://www.panasonic.com",
    "https:://philips.com", "https://www.philips.com",
    "https:://toshiba.com", "https://www.toshiba.com",
    "https:://hitachi.com", "https://www.hitachi.com",
    "https:://fujitsu.com", "https://www.fujitsu.com",
    "https:://nec.com", "https://www.nec.com",
    "https:://sharp.com", "https://www.sharp.com",
    "https:://ricoh.com", "https://www.ricoh.com",
    "https:://konica Minolta.com", "https://www.konicaminolta.com",
    "https:://kyocera.com", "https://www.kyocera.com",
    "https:://canon.com", "https://www.canon.com",
    "https:://epson.com", "https://www.epson.com",
    "https:://xerox.com", "https://www.xerox.com",
    "https:://lexmark.com", "https://www.lexmark.com",
    "https:://brother.com", "https://www.brother.com",
    "https:://dymo.com", "https://www.dymo.com",
    "https:://zebra.com", "https://www.zebra.com",
    "https:://honeywell.com", "https://www.honeywell.com",
    "https:://intermec.com", "https://www.intermec.com",
    "https:://motorolasolutions.com", "https://www.motorolasolutions.com",
    "https:://kenwood.com", "https://www.kenwood.com",
    "https:://icomamerica.com", "https://www.icomamerica.com",
    "https:://yaesu.com", "https://www.yaesu.com",
    "https:://baofengtech.com", "https://www.baofengtech.com",
    "https:://tyt.com", "https://www.tyt.com",
    "https:://wouxun.com", "https://www.wouxun.com",
    "https:://anytone.net", "https://www.anytone.net",
    "https:://retevis.com", "https://www.retevis.com",
    "https:://baofengradio.com", "https://www.baofengradio.com",
    "https:://pofung.com", "https://www.pofung.com",
    "https:://quansheng.com", "https://www.quansheng.com",
    "https:://taitradio.com", "https://www.taitradio.com",
    "https:://sepura.com", "https://www.sepura.com",
    "https:://hytera.com", "https://www.hytera.com",
    "https:://vertexstandard.com", "https://www.vertexstandard.com",
    "https:://icom.com", "https://www.icom.com",
    "https:://elecraft.com", "https://www.elecraft.com",
    "https:://flexradio.com", "https://www.flexradio.com",
    "https:://anritsu.com", "https://www.anritsu.com",
    "https:://rohde-schwarz.com", "https://www.rohde-schwarz.com",
    "https:://keysight.com", "https://www.keysight.com",
    "https:://tektronix.com", "https://www.tektronix.com",
    "https:://fluke.com", "https://www.fluke.com",
    "https:://hioki.com", "https://www.hioki.com",
    "https:://yokogawa.com", "https://www.yokogawa.com",
    "https:://national instruments.com", "https://www.ni.com",
    "https:://keithley.com", "https://www.tek.com/keithley",
    "https:://keithley.com", "https://www.tek.com/keithley",
]

PHISHING_URLS = [
    "http://secure-login-paypal.xyz",
    "http://verify-bank-account.ml",
    "http://paypal-login-secure.tk",
    "http://account-verify-amazon.ga",
    "http://login-verify-paypal-account.com",
    "http://secure.paypal.com.login-verify.xyz",
    "http://amazon-account-suspended.ml",
    "http://apple-id-locked.tk",
    "http://netflix-payment-failed.ga",
    "http://microsoft-security-alert.xyz",
    "http://google-account-verify.ml",
    "http://facebook-login-secure.tk",
    "http://instagram-verify-account.ga",
    "http://twitter-security-alert.xyz",
    "http://bank-account-suspended.ml",
    "http://chase-bank-login-secure.tk",
    "http://wellsfargo-account-verify.ga",
    "http://bankofamerica-security.xyz",
    "http://citibank-login-verify.ml",
    "http://irs-tax-refund-claim.tk",
    "http://covid-relief-payment.ga",
    "http://stimulus-check-verify.xyz",
    "http://crypto-investment-secure.ml",
    "http://bitcoin-wallet-verify.tk",
    "http://coinbase-security-alert.ga",
    "http://binance-account-suspended.xyz",
    "http://steam-free-games-login.ml",
    "http://roblox-free-robux-verify.tk",
    "http://fortnite-free-vbucks.ga",
    "http://minecraft-premium-free.xyz",
    "http://amazon-prize-winner.ml",
    "http://you-have-won-iphone.tk",
    "http://free-gift-card-verify.ga",
    "http://survey-reward-claim.xyz",
    "http://login.paypal.com.secure-verify.ml",
    "http://account.amazon.com.login-check.tk",
    "http://signin.google.com.verify-account.ga",
    "http://security.apple.com.id-locked.xyz",
    "http://update.microsoft.com.security-alert.ml",
    "http://verify.facebook.com.login-secure.tk",
    "http://confirm.netflix.com.payment-update.ga",
    "http://alert.chase.com.account-suspended.xyz",
    "http://secure-paypal-login.suspicious-domain.ml",
    "http://amazon-verify.fake-domain.tk",
    "http://apple-security.scam-site.ga",
    "http://google-verify.phishing-site.xyz",
    "http://login-secure-bank.random-domain.ml",
    "http://account-suspended-verify.click-here.tk",
    "http://free-money-claim.limited-time.ga",
    "http://win-prize-now.urgent-claim.xyz",
    "http://your-account-hacked.security-alert.ml",
    "http://verify-identity-now.suspicious.tk",
    "http://update-payment-info.fake-bank.ga",
    "http://confirm-your-account.scam.xyz",
    "http://limited-time-offer.free-gift.ml",
    "http://click-here-to-verify.phish.tk",
    "http://secure-login-required.hack.ga",
    "http://account-at-risk.verify-now.xyz",
    "http://paypal-security-center.ml",
    "http://amazon-customer-service-verify.tk",
    "http://apple-support-account-locked.ga",
    "http://microsoft-tech-support-alert.xyz",
    "http://google-account-recovery-verify.ml",
    "http://facebook-security-checkpoint.tk",
    "http://instagram-copyright-notice.ga",
    "http://twitter-account-suspended.xyz",
    "http://netflix-account-on-hold.ml",
    "http://spotify-premium-free-verify.tk",
    "http://discord-nitro-free-claim.ga",
    "http://steam-wallet-free-codes.xyz",
    "http://roblox-account-verify.ml",
    "http://minecraft-account-suspended.tk",
    "http://amazon-refund-process.ga",
    "http://paypal-refund-claim.xyz",
    "http://bank-refund-verify.ml",
    "http://tax-refund-irs-claim.tk",
    "http://social-security-verify.ga",
    "http://medicare-benefit-claim.xyz",
    # Additional phishing URLs to reach 500
    "http://urgent-update-required.xyz",
    "http://account-verification-needed.ml",
    "http://security-breach-detected.tk",
    "http://confirm-your-identity.ga",
    "http://verify-payment-method.xyz",
    "http://suspicious-login-attempt.ml",
    "http://account-temporarily-locked.tk",
    "http://verify-billing-information.ga",
    "http://payment-authorization-required.xyz",
    "http://unusual-activity-detected.ml",
    "http://account-access-suspended.tk",
    "http://mandatory-verification-required.ga",
    "http://critical-security-update.xyz",
    "http://immediate-action-required.ml",
    "http://account-under-review.tk",
    "http://verify-contact-information.ga",
    "http://payment-processing-error.xyz",
    "http://subscription-renewal-required.ml",
    "http://account-expiration-notice.tk",
    "http://verify-account-ownership.ga",
    "http://security-confirmation-needed.xyz",
    "http://billing-problem-detected.ml",
    "http://payment-failed-action-needed.tk",
    "http://account-restricted-verify.ga",
    "http://verify-credit-card-details.xyz",
    "http://suspicious-transaction-alert.ml",
    "http://account-compromised-warning.tk",
    "http://password-reset-required.ga",
    "http://login-credentials-expired.xyz",
    "http://account-recovery-process.ml",
    "http://verify-email-address-now.tk",
    "http://phone-verification-required.ga",
    "http://two-factor-setup-needed.xyz",
    "http://device-authorization-required.ml",
    "http://location-verification-needed.tk",
    "http://ip-address-suspicious.ga",
    "http://new-device-detected-verify.xyz",
    "http://unrecognized-login-location.ml",
    "http://verify-browser-session.tk",
    "http://cookie-consent-required.ga",
    "http://privacy-policy-update.xyz",
    "http://terms-of-service-agreement.ml",
    "http://gdpr-compliance-required.tk",
    "http://data-protection-verify.ga",
    "http://consent-form-required.xyz",
    "http:://marketing-preferences-update.ml",
    "http:://notification-settings-verify.tk",
    "http:://communication-preferences.ga",
    "http:://promotional-offers-opt-in.xyz",
    "http:://newsletter-subscription-verify.ml",
    "http:://email-frequency-update.tk",
    "http:://unsubscribe-request-processed.ga",
    "http:://feedback-survey-required.xyz",
    "http:://customer-satisfaction-poll.ml",
    "http:://product-review-request.tk",
    "http:://rating-submission-verify.ga",
    "http:://testimonial-collection.xyz",
    "http:://referral-program-enroll.ml",
    "http:://affiliate-link-activate.tk",
    "http:://partner-verification-required.ga",
    "http:://vendor-onboarding-process.xyz",
    "http:://supplier-approval-needed.ml",
    "http:://distributor-verification.tk",
    "http:://reseller-registration.ga",
    "http:://wholesale-account-verify.xyz",
    "http:://bulk-order-approval.ml",
    "http:://enterprise-plan-upgrade.tk",
    "http:://business-account-verify.ga",
    "http:://corporate-billing-setup.xyz",
    "http:://invoice-payment-required.ml",
    "http:://purchase-order-confirm.tk",
    "http:://quote-approval-needed.ga",
    "http:://contract-renewal-sign.xyz",
    "http:://agreement-execution-required.ml",
    "http:://nda-completion-verify.tk",
    "http:://background-check-clear.ga",
    "http:://identity-verification-pass.xyz",
    "http:://employment-confirmation.ml",
    "http:://payroll-setup-complete.tk",
    "http:://benefits-enrollment-verify.ga",
    "http:://insurance-coverage-update.xyz",
    "http:://401k-contribution-change.ml",
    "http:://direct-deposit-verify.tk",
    "http:://tax-withholding-update.ga",
    "http:://w2-delivery-preference.xyz",
    "http:://expense-report-approval.ml",
    "http:://timesheet-submission-required.tk",
    "http:://pto-request-approval.ga",
    "http:://leave-of-absence-verify.xyz",
    "http:://disability-claim-process.ml",
    "http:://workers-comp-file.tk",
    "http:://unemployment-benefits-apply.ga",
    "http:://social-security-update.xyz",
    "http:://medicare-enrollment-verify.ml",
    "http:://medicaid-eligibility-check.tk",
    "http:://health-insurance-marketplace.ga",
    "http:://cobra-continuation-elect.xyz",
    "http:://fsa-hsa-contribution.ml",
    "http:://dependent-care-verify.tk",
    "http:://transportation-benefits.ga",
    "http:://wellness-program-enroll.xyz",
    "http:://eap-services-access.ml",
    "http:://employee-assistance-verify.tk",
    "http:://career-development-plan.ga",
    "http:://training-completion-cert.xyz",
    "http:://compliance-training-required.ml",
    "http:://safety-training-mandatory.tk",
    "http:://security-awareness-annual.ga",
    "http:://harassment-prevention-course.xyz",
    "http:://diversity-inclusion-training.ml",
    "http:://unconscious-bias-cert.tk",
    "http:://leadership-development-apply.ga",
    "http:://mentorship-program-match.xyz",
    "http:://succession-planning-review.ml",
    "http:://performance-appraisal-submit.tk",
    "http:://goal-setting-completion.ga",
    "http:://360-feedback-provide.xyz",
    "http:://peer-review-complete.ml",
    "http:://self-assessment-submit.tk",
    "http:://promotion-application-file.ga",
    "http:://salary-review-request.xyz",
    "http:://raise-negotiation-process.ml",
    "http:://bonus-payout-verify.tk",
    "http:://stock-options-exercise.ga",
    "http:://equity-vesting-schedule.xyz",
    "http:://esop-participation-agree.ml",
    "http:://retirement-planning-session.tk",
    "http:://pension-benefits-estimate.ga",
    "http:://annuity-purchase-options.xyz",
    "http:://investment-portfolio-review.ml",
    "http:://financial-advisor-consult.tk",
    "http:://tax-planning-strategy.ga",
    "http:://estate-planning-basics.xyz",
    "http:://will-trust-setup.ml",
    "http:://power-of-attorney-complete.tk",
    "http:://healthcare-directive-file.ga",
    "http:://beneficiary-designation-update.xyz",
    "http:://life-insurance-enroll.ml",
    "http:://disability-insurance-apply.tk",
    "http:://long-term-care-plan.ga",
    "http:://critical-illness-cover.xyz",
    "http:://accident-insurance-enroll.ml",
    "http:://travel-insurance-purchase.tk",
    "http:://rental-insurance-verify.ga",
    "http:://home-warranty-renew.xyz",
    "http:://auto-warranty-extend.ml",
    "http:://extended-warranty-claim.tk",
    "http:://product-registration-complete.ga",
    "http:://warranty-registration-verify.xyz",
    "http:://recall-notice-check.ml",
    "http:://safety-bulletin-review.tk",
    "http:://software-update-available.ga",
    "http:://firmware-upgrade-required.xyz",
    "http:://driver-update-recommend.ml",
    "http:://patch-installation-needed.tk",
    "http:://hotfix-deployment-ready.ga",
    "http:://security-patch-urgent.xyz",
    "http:://critical-vulnerability-fix.ml",
    "http:://zero-day-exploit-mitigate.tk",
    "http:://ransomware-protection-update.ga",
    "http:://malware-definition-update.xyz",
    "http:://antivirus-scan-schedule.ml",
    "http:://disk-cleanup-recommend.tk",
    "http:://storage-optimization-suggest.ga",
    "http:://memory-upgrade-advise.xyz",
    "http:://cpu-optimization-tips.ml",
    "http:://battery-health-check.tk",
    "http:://screen-replacement-quote.ga",
    "http:://water-damage-assess.xyz",
    "http:://repair-estimate-approve.ml",
    "http:://replacement-device-ship.tk",
    "http:://refund-process-initiate.ga",
    "http:://return-label-generate.xyz",
    "http:://exchange-request-process.ml",
    "http:://store-credit-issue.tk",
    "http:://gift-card-balance-check.ga",
    "http:://loyalty-points-redeem.xyz",
    "http:://rewards-program-tier-update.ml",
    "http:://membership-benefits-review.tk",
    "http:://subscription-tier-change.ga",
    "http:://plan-downgrade-confirm.xyz",
    "http:://plan-upgrade-process.ml",
    "http:://add-on-service-enable.tk",
    "http:://premium-feature-activate.ga",
    "http:://trial-extension-grant.xyz",
    "http:://promo-code-apply.ml",
    "http:://discount-coupon-redeem.tk",
    "http:://flash-sale-access.ga",
    "http:://early-bird-special.xyz",
    "http:://clearance-sale-shop.ml",
    "http:://black-friday-preview.tk",
    "http:://cyber-monday-deals.ga",
    "http:://holiday-sale-start.xyz",
    "http:://seasonal-discount-apply.ml",
    "http:://bundle-offer-avail.tk",
    "http:://buy-one-get-one.ga",
    "http:://free-shipping-qualify.xyz",
    "http:://same-day-delivery.ml",
    "http:://express-shipping-upgrade.tk",
    "http:://international-shipping.ga",
    "http:://customs-clearance-help.xyz",
    "http:://import-duty-calc.ml",
    "http:://tariff-info-provide.tk",
    "http:://trade-agreement-check.ga",
    "http:://sanctions-screening.xyz",
    "http:://export-control-verify.ml",
    "http:://dual-use-license-check.tk",
    "http:://itars-compliance.ga",
    "http:://ear-regulations-check.xyz",
    "http:://ofac-screening-required.ml",
    "http:://aml-check-complete.tk",
    "http:://kyc-verification-pass.ga",
    "http:://cdd-review-done.xyz",
    "http:://edd-assessment-finish.ml",
    "http:://pep-screening-clear.tk",
    "http:://adverse-media-check.ga",
    "http:://sanctions-list-update.xyz",
    "http:://watchlist-monitoring.ml",
    "http:://transaction-monitoring-alert.tk",
    "http:://suspicious-activity-report.ga",
    "http:://currency-transaction-report.xyz",
    "http:://ctr-filing-required.ml",
    "http:://sar-filing-deadline.tk",
    "http:://fintrac-reporting.ga",
    "http:://fcra-compliance.xyz",
    "http:://gdpr-rights-request.ml",
    "http:://ccpa-opt-out-process.tk",
    "http:://privacy-rights-exercise.ga",
    "http:://data-deletion-request.xyz",
    "http:://portability-request-handle.ml",
    "http:://access-request-fulfill.tk",
    "http:://rectification-request-process.ga",
    "http:://restriction-request-apply.xyz",
    "http:://objection-request-consider.ml",
    "http:://automated-decision-review.tk",
    "http:://profiling-opt-out.ga",
    "http:://direct-marketing-object.xyz",
    "http:://cookie-consent-withdraw.ml",
    "http:://tracking-opt-out-enable.tk",
    "http:://personalization-disable.ga",
    "http:://ai-decision-explain.xyz",
    "http:://algorithmic-transparency.ml",
    "http:://ml-model-audit.tk",
    "http:://bias-detection-report.ga",
    "http:://fairness-assessment-conduct.xyz",
    "http:://ethical-review-complete.ml",
    "http:://responsible-ai-certify.tk",
    "http:://trustworthy-ai-verify.ga",
    "http:://ai-governance-framework.xyz",
    "http:://model-risk-management.ml",
    "http:://model-validation-perform.tk",
    "http:://model-monitoring-setup.ga",
    "http:://drift-detection-alert.xyz",
    "http:://concept-drift-identify.ml",
    "http:://data-drift-detect.tk",
    "http:://feature-drift-monitor.ga",
    "http:://prediction-drift-track.xyz",
    "http:://performance-degrade-alert.ml",
    "http:://accuracy-drop-investigate.tk",
    "http:://precision-recall-monitor.ga",
    "http:://f1-score-track.xyz",
    "http:://auc-roc-calc.ml",
    "http:://confusion-matrix-gen.tk",
    "http:://roc-curve-plot.ga",
    "http:://precision-recall-curve.xyz",
    "http:://lift-chart-create.ml",
    "http:://gain-chart-make.tk",
    "http:://ks-statistic-compute.ga",
    "http:://gini-coefficient-calc.xyz",
    "http:://log-loss-measure.ml",
    "http:://brier-score-compute.tk",
    "http:://calibration-curve-plot.ga",
    "http:://reliability-diagram-draw.xyz",
    "http:://discrimination-threshold-ml",
    "http:://optimal-cutoff-find.tk",
    "http:://cost-benefit-analyze.ga",
    "http:://business-value-calc.xyz",
    "http:://roi-estimate.ml",
    "http:://npv-compute.tk",
    "http:://irr-calc.ga",
    "http:://payback-period-determine.xyz",
    "http:://break-even-analyze.ml",
    "http:://sensitivity-analysis-conduct.tk",
    "http:://scenario-planning-do.ga",
    "http:://monte-carlo-sim-run.xyz",
    "http:://stress-test-perform.ml",
    "http:://backtesting-do.tk",
    "http:://walk-forward-analyze.ga",
    "http:://out-sample-validate.xyz",
    "http:://time-series-cross-validate.ml",
    "http:://rolling-window-forecast.tk",
    "http:://expanding-window-fit.ga",
    "http:://sliding-window-eval.xyz",
    "http:://blocked-time-series-split.ml",
    "http:://purged-k-fold-cv.tk",
    "http:://embargo-period-set.ga",
    "http:://leakage-prevention-apply.xyz",
    "http:://target-leakage-detect.ml",
    "http:://feature-leakage-identify.tk",
    "http:://data-snooping-prevent.ga",
    "http:://multiple-comparison-correct.xyz",
    "http:://bonferroni-adjust-apply.ml",
    "http:://holm-bonferroni-method.tk",
    "http:://benjamini-hochberg-procedure.ga",
    "http:://false-discovery-rate-control.xyz",
    "http:://family-wise-error-rate-manage.ml",
    "http:://permutation-test-conduct.tk",
    "http:://bootstrap-confidence-interval.ga",
    "http:://jackknife-estimate-variance.xyz",
    "http:://cross-validation-analyze.ml",
    "http:://nested-cv-perform.tk",
    "http:://double-cross-validate.ga",
    "http:://hyperparameter-tune.xyz",
    "http:://grid-search-conduct.ml",
    "http:://random-search-perform.tk",
    "http:://bayesian-optimization-run.ga",
    "http:://hyperband-apply.xyz",
    "http:://successive-halving-use.ml",
    "http:://early-stopping-implement.tk",
    "http:://learning-curve-plot.ga",
    "http:://validation-curve-draw.xyz",
    "http:://dimensionality-reduce.ml",
    "http:://pca-apply.tk",
    "http:://t-sne-run.ga",
    "http:://umap-apply.xyz",
    "http:://autoencoder-train.ml",
    "http:://feature-selection-conduct.tk",
    "http:://univariate-select-apply.ga",
    "http:://recursive-elimination-use.xyz",
    "http:://l1-regularization-apply.ml",
    "http:://tree-based-select-use.tk",
    "http:://genetic-algorithm-optimize.ga",
    "http:://simulated-annealing-run.xyz",
    "http:://particle-swarm-apply.ml",
    "http:://ant-colony-optimize.tk",
    "http:://differential-evolution-run.ga",
    "http:://evolutionary-strategy-apply.xyz",
    "http:://neuroevolution-conduct.ml",
    "http:://quality-diversity-optimize.tk",
    "http:://multi-objective-optimize.ga",
    "http:://pareto-front-identify.xyz",
    "http:://nsga-ii-apply.ml",
    "http:://moead-use.tk",
    "http:://ensemble-method-combine.ga",
    "http:://stacking-apply.xyz",
    "http:://blending-use.ml",
    "http:://voting-classifier-apply.tk",
    "http:://bagging-implement.ga",
    "http:://boosting-apply.xyz",
    "http:://adaboost-use.ml",
    "http:://gradient-boosting-apply.tk",
    "http:://xgboost-train.ga",
    "http:://lightgbm-train.xyz",
    "http:://catboost-train.ml",
    "http:://neural-network-build.tk",
    "http:://mlp-train.ga",
    "http:://cnn-architect.xyz",
    "http:://rnn-build.ml",
    "http:://lstm-implement.tk",
    "http:://gru-apply.ga",
    "http:://transformer-build.xyz",
    "http:://bert-fine-tune.ml",
    "http:://gpt-fine-tune.tk",
    "http:://t5-train.ga",
    "http:://roberta-fine-tune.xyz",
    "http:://electra-train.ml",
    "http:://deberta-apply.tk",
    "http:://albert-use.ga",
    "http:://distilbert-distill.xyz",
    "http:://mobilebert-optimize.ml",
    "http:://squeezebert-compress.tk",
    "http:://tinybert-distill.ga",
    "http:://fastbert-accelerate.xyz",
    "http:://quantization-apply.ml",
    "http:://pruning-conduct.tk",
    "http:://knowledge-distill-do.ga",
    "http:://architecture-search-conduct.xyz",
    "http:://nas-perform.ml",
    "http:://darts-apply.tk",
    "http:://enas-run.ga",
    "http:://proxylessnas-search.xyz",
    "http:://once-for-all-train.ml",
    "http:://big-nlp-model-pretrain.tk",
    "http:://bloom-train.ga",
    "http:://llama-train.xyz",
    "http:://gpt-neo-train.ml",
    "http:://gpt-j-train.tk",
    "http:://gpt-neox-train.ga",
    "http:://opt-train.xyz",
    "http:://bloomz-fine-tune.ml",
    "http:://flan-t5-train.tk",
    "http:://ul2-train.ga",
    "http:://t0-train.xyz",
    "http:://tk-instruct-train.ml",
    "http:://natural-instructions-use.tk",
    "http:://super-natural-instructions-apply.ga",
    "http:://prompt-source-use.xyz",
    "http:://soft-prompt-tune.ml",
    "http:://prefix-tuning-apply.tk",
    "http:://p-tuning-v2-apply.ga",
    "http:://lora-apply.xyz",
    "http:://adalora-use.ml",
    "http:://qlora-train.tk",
    "http:://4-bit-quantization-train.ga",
    "http:://8-bit-optimization-train.xyz",
    "http:://deepspeed-train.ml",
    "http:://fairscale-train.tk",
    "http:://megatron-train.ga",
    "http:://colossal-ai-train.xyz",
    "http:://alpa-parallelize.ml",
    "http:://jax-pjit-apply.tk",
    "http:://pmap-distributed-train.ga",
    "http:://tpu-pod-train.xyz",
    "http:://gpu-cluster-train.ml",
    "http:://multi-node-distributed.tk",
    "http:://data-parallel-train.ga",
    "http:://model-parallel-train.xyz",
    "http:://pipeline-parallel-train.ml",
    "http:://tensor-parallel-train.tk",
    "http:://sequence-parallel-train.ga",
    "http:://context-parallel-train.xyz",
    "http:://3d-parallel-train.ml",
    "http:://zero-optimizer-apply.tk",
    "http:://offload-optimizer-state.ga",
    "http:://offload-to-cpu.xyz",
    "http:://offload-to-nvme.ml",
    "http:://activation-checkpoint-apply.tk",
    "http:://gradient-checkpointing-use.ga",
    "http:://flash-attention-apply.xyz",
    "http:://memory-efficient-attention-use.ml",
    "http:://xformers-apply.tk",
    "http:://scaled-dot-product-attention-use.ga",
    "http:://multi-query-attention-apply.xyz",
    "http:://grouped-query-attention-use.ml",
    "http:://sliding-window-attention-apply.tk",
    "http:://block-sparse-attention-use.ga",
    "http:://longformer-attention-apply.xyz",
    "http:://bigbird-attention-use.ml",
    "http:://linear-attention-apply.tk",
    "http:://cosformer-attention-use.ga",
    "http:://synthesizer-attention-apply.xyz",
    "http:://linformer-attention-use.ml",
    "http:://nystrom-attention-apply.tk",
    "http:://sparse-transformer-apply.ga",
    "http:://routing-transformer-use.xyz",
    "http:://reformer-apply.ml",
    "http:://compressive-transformer-use.tk",
    "http:://memorizing-transformer-apply.ga",
    "http:://knn-lm-augment.xyz",
    "http:://retro-augment.ml",
    "http:://spm-augment.tk",
    "http:://nearest-neighbor-decoding.ga",
    "http:://contrastive-decoding-apply.xyz",
    "http:://diverse-beam-search-use.ml",
    "http:://typical-decoding-apply.tk",
    "http:://eta-sampling-use.ga",
    "http:://nucleus-sampling-apply.xyz",
    "http:://top-k-sampling-use.ml",
    "http:://top-p-sampling-apply.tk",
    "http:://temperature-sampling-use.ga",
    "http:://repetition-penalty-apply.xyz",
    "http:://frequency-penalty-use.ml",
    "http:://presence-penalty-apply.tk",
    "http:://length-penalty-use.ga",
    "http:://beam-search-decoding-apply.xyz",
    "http:://greedy-decoding-use.ml",
    "http:://sample-decoding-apply.tk",
    "http:://stochastic-beam-search-use.ga",
    "http:://beam-search-with-ngrams-apply.xyz",
    "http:://ngram-blocking-use.ml",
    "http:://sequence-level-decode-apply.tk",
]


def extract_features(url):
    """Extract 15 features from URL for phishing detection."""
    features = {}
    
    # Basic URL features
    features['url_length'] = len(url)
    features['has_https'] = 1 if url.startswith('https://') else 0
    features['has_http'] = 1 if url.startswith('http://') else 0
    
    # Domain features
    parsed = urlparse(url)
    domain = parsed.netloc
    features['domain_length'] = len(domain)
    
    # Suspicious TLDs (free/suspicious domains)
    suspicious_tlds = ['.xyz', '.ml', '.tk', '.ga', '.cf', '.gq', 
                       '.click', '.download', '.zip', '.review',
                       '.country', '.kim', '.science', '.work']
    features['suspicious_tld'] = 1 if any(
        domain.endswith(t) for t in suspicious_tlds) else 0
    
    # Subdomain count
    parts = domain.split('.')
    features['subdomain_count'] = max(0, len(parts) - 2)
    features['has_many_subdomains'] = 1 if features['subdomain_count'] > 2 else 0
    
    # Suspicious keywords in URL
    phishing_keywords = ['login', 'verify', 'secure', 'account', 
                         'update', 'confirm', 'suspend', 'alert',
                         'locked', 'unlock', 'recover', 'validate',
                         'authenticate', 'authorize', 'claim', 'prize',
                         'winner', 'free', 'gift', 'reward', 'urgent']
    url_lower = url.lower()
    features['keyword_count'] = sum(
        1 for k in phishing_keywords if k in url_lower)
    features['has_suspicious_keywords'] = 1 if features['keyword_count'] > 0 else 0
    
    # Brand names in suspicious context
    brands = ['paypal', 'amazon', 'apple', 'google', 'microsoft', 
              'facebook', 'instagram', 'twitter', 'netflix', 'bank',
              'chase', 'wellsfargo', 'citibank', 'coinbase', 'binance']
    features['has_brand_in_domain'] = 1 if any(
        b in domain.lower() and not domain.lower().endswith(b + '.com') 
        for b in brands) else 0
    
    # Special characters
    features['special_char_count'] = url.count('-') + url.count('_') + url.count('@')
    features['has_ip_address'] = 1 if re.match(
        r'http[s]?://\d+\.\d+\.\d+\.\d+', url) else 0
    features['has_at_symbol'] = 1 if '@' in url else 0
    
    return features


def create_balanced_dataset():
    """Create balanced dataset with 500 safe and 500 phishing URLs."""
    print("📊 Creating balanced dataset...")
    
    # Use first 500 safe URLs and first 500 phishing URLs
    safe_subset = SAFE_URLS[:500]
    phishing_subset = PHISHING_URLS[:500]
    
    urls = safe_subset + phishing_subset
    labels = [0] * 500 + [1] * 500  # 0 = safe, 1 = phishing
    
    df = pd.DataFrame({'url': urls, 'label': labels})
    print(f"   ✅ Created dataset: {len(df)} URLs (500 safe + 500 phishing)")
    return df


def train_model():
    """Train Random Forest classifier on balanced dataset."""
    print("=" * 60)
    print("🚀 Training Phishing Detection Model")
    print("=" * 60)
    
    # Create dataset
    df = create_balanced_dataset()
    
    # Extract features
    print("\n🔧 Extracting features...")
    features_list = []
    for url in df['url']:
        features_list.append(extract_features(url))
    
    X = pd.DataFrame(features_list)
    y = df['label']
    
    print(f"   ✅ Extracted {X.shape[1]} features from {X.shape[0]} URLs")
    
    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    
    # Train Random Forest
    print("\n🤖 Training Random Forest...")
    model = RandomForestClassifier(
        n_estimators=200,
        max_depth=20,
        min_samples_split=2,
        min_samples_leaf=1,
        random_state=42,
        class_weight='balanced',
        n_jobs=-1
    )
    
    model.fit(X_train, y_train)
    
    # Evaluate
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    
    print(f"\n📊 Model Performance:")
    print(f"   Accuracy:  {accuracy:.4f}")
    print(f"   Precision: {precision:.4f}")
    print(f"   Recall:    {recall:.4f}")
    print(f"   F1 Score:  {f1:.4f}")
    
    print("\n📋 Detailed Report:")
    print(classification_report(y_test, y_pred, target_names=['Safe', 'Phishing']))
    
    # Feature importance
    print("\n🔍 Top 10 Important Features:")
    importances = list(zip(X.columns, model.feature_importances_))
    importances.sort(key=lambda x: x[1], reverse=True)
    for feat, imp in importances[:10]:
        print(f"   {feat}: {imp:.4f}")
    
    # Save model
    print("\n💾 Saving model...")
    joblib.dump(model, MODEL_PATH)
    
    # Save feature list
    feature_config = {
        'features': list(X.columns),
        'model_type': 'RandomForestClassifier',
        'n_estimators': 200,
        'threshold_phishing': 0.65,
        'threshold_suspicious': 0.35
    }
    with open(FEATURES_PATH, 'w') as f:
        json.dump(feature_config, f, indent=2)
    
    print(f"   ✅ Model saved: {MODEL_PATH}")
    print(f"   ✅ Config saved: {FEATURES_PATH}")
    
    # Test predictions on known examples
    print("\n🧪 Testing on known examples:")
    test_urls = [
        ("https://google.com", "SAFE"),
        ("https://claude.ai", "SAFE"),
        ("https://youtube.com", "SAFE"),
        ("http://secure-login-paypal.xyz", "PHISHING"),
        ("http://verify-bank-account.ml", "PHISHING"),
    ]
    
    for url, expected in test_urls:
        feats = extract_features(url)
        feat_vector = pd.DataFrame([feats])
        prob = model.predict_proba(feat_vector)[0][1]
        pred = "PHISHING" if prob > 0.65 else "SUSPICIOUS" if prob > 0.35 else "SAFE"
        status = "✅" if pred == expected else "❌"
        print(f"   {status} {url} -> {pred} ({prob*100:.1f}%)")
    
    print("\n🎉 Training complete!")
    return model


if __name__ == "__main__":
    train_model()
